spring:
  application:
    name: oauth-resource-service    # 서비스 ID (컨피그 클라이언트가 어떤 서비스를 조회하는지 매핑)
  profiles:
    active: local         # 서비스가 실행할 기본 프로파일

  cloud:
    config:
      uri: http://localhost:8889  # Config Server 위치
your.name: "eaton Default Modify Resource1gggggg"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      ebabked: true  
eureka:   ## 추가
  instance:
    instance-id: oauth-resource-instance
    prefer-ip-address: false       ## 서비스 이름 대신 IP 주소 등록
    lease-renewal-interval-in-seconds: 3  # 디스커버리한테 3초마다 하트비트 전송 (디폴트 30초)
    lease-expiration-duration-in-seconds: 2 # 디스커버리는 서비스 등록 해제 하기 전에 마지막 하트비트에서부터 설정된 시간(second) 기다린 후 서비스 등록 해제 (디폴트 90초)
  client:
    register-with-eureka: true    ## Eureka Server 에 서비스 등록
    fetch-registry: true          ## 레지스트리 정보를 로컬에 캐싱
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
