your.name: "eaton Default Modify!!!"
member.service.id: "TTTTT"
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: '{cipher}d29b12c27b7e81464503b5047e7c2d9eca91ec85909d9b9c05c256c0847df4fe'
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      ebabked: true  
eureka:   ## 추가
  instance:
    prefer-ip-address: true       ## 서비스 이름 대신 IP 주소 등록
    lease-renewal-interval-in-seconds: 3  # 디스커버리한테 3초마다 하트비트 전송 (디폴트 30초)
    lease-expiration-duration-in-seconds: 2 # 디스커버리는 서비스 등록 해제 하기 전에 마지막 하트비트에서부터 설정된 시간(second) 기다린 후 서비스 등록 해제 (디폴트 90초)
  client:
    register-with-eureka: true    ## Eureka Server 에 서비스 등록
    fetch-registry: true          ## 레지스트리 정보를 로컬에 캐싱
